apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhblZ6ZEROcGN5MWtaWFk2WjJod1gwUnVRWGhJVVZkVVJteE9VemsxZW5aSWNqSkxka3hqYWt0VE1sZEJlakIwU1RoUlVRPT0iCgkJfQoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9Cg==
type: kubernetes.io/dockerconfigjson
